name : first-demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn verify jacoco:report
            
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html
          
      - name: Run SonarQube Scanner
        env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "https://sonarcloud.io"
        run: |
          mvn sonar:sonar `
            -Dsonar.projectKey=sonardemo `
            -Dsonar.organization=vcjain `
            -Dsonar.host.url=$env:SONAR_HOST_URL `
            -Dsonar.login=$env:SONAR_TOKEN